### ISSUE TITLE
使用Mysql作为数据库时，不会自动建表

### ISSUE THREAD

**Issue by Crush0** [cssxsh/mirai-economy-core#10]
我的hibernate.properties配置如下，但是在启动mirai后数据库中没有创建表，导致插件在调用表时提示找不到表economy_balance_record和economy_account_record
`hibernate.connection.url=jdbc:mysql://xxxxx:3306/mirai?autoReconnect=true`
`hibernate.connection.CharSet=utf8mb4`
`hibernate.dialect=org.hibernate.dialect.MySQLDialect`
`hibernate.connection.useUnicode=true`
`hibernate.connection.username=mirai`
`hibernate.connection.password=xxxxx`
`hibernate.connection.provider_class=org.hibernate.hikaricp.internal.HikariCPConnectionProvider`
`hibernate.connection.isolation=1`
`hibernate.hbm2ddl.auto=update`

**Comment by cssxsh** [comment]
请检查日志中是否有相关报错
