### ISSUE TITLE
申请添加功能:添加一个自定义全局经济上下文

### ISSUE THREAD

**Issue by Moyuyanli** [cssxsh/mirai-economy-core#9]
默认的全局上下文只有一个，bot上下文的话，如果bot被风控，那么在bot里面的上下文就用不了了，想要一个第二个全局上下文。

**Comment by cssxsh** [comment]
https://github.com/cssxsh/mirai-economy-core/commit/0247a1af15efb339080c9b6afea7a3649d2f2e52
